### ISSUE TITLE
Regression in 0.6.6: unknown tool name "rustdoc::all"?

### ISSUE THREAD

**Issue by dkegel-fastly** [sunfishcode/unsafe-io#9]
Our app (which does not depend directly on unsafe-io) broke today with this error:

15:09:03  error[E0710]: an unknown tool name found in scoped lint: `rustdoc::all`
15:09:03     --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/unsafe-io-0.6.8/src/lib.rs:205:5
15:09:03      |
15:09:03  205 |     rustdoc::all,
15:09:03      |     ^^^^^^^

Evidently https://github.com/sunfishcode/unsafe-io/commit/fa2cc81a8715f08972775195e331dee00a46bb50 was not as safe as it seemed?

I haven't had any luck in figuring out whether rustdoc::all is something that was added in a newer rust or what... I'm a total rust newbie :-(

**Comment by sunfishcode** [comment]
Sorry for the breakage here; yes, it appears rustdoc::all is just added in Rust 1.52.0, a recent release. It's just enabling some compiler lints, so it isn't anything essential, so I'll just disable it for now.

**Comment by sunfishcode** [comment]
I removed the `rustdoc::all` in 7f0909c4ca2f7c468a4a6e96f571b8c581459efb, which is now published as 0.6.9.
